/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance.management.system;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class feedback extends javax.swing.JFrame {

    /**
     * Creates new form feedback
     */
    String username;
    public feedback() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FEEDBACK ABOUT ATTENDANCE");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("SEND FEEDBACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton1)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!jTextArea1.getText().equals("") ){
            
        this.username= jTextArea1.getText();
        
        
       
                  if(checkExist()){
                                              //  password=new String(encrypt(password));                   
                                                String accinfo =username;
                                                saveToFile("feedback.txt",accinfo);
                                   JOptionPane.showMessageDialog(null,"feedback Done","Information Save",JOptionPane.OK_OPTION,null);
                                           }else{
                                        System.out.println("erroe in checklist "); 
                                           }
                  
                                    
                                    }    
                        else {JOptionPane.showMessageDialog(null,"Fill All Details","Invalid",JOptionPane.ERROR_MESSAGE);}
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
public boolean checkExist() {
        String filename="feedback.txt";
          FileReader fr;
          BufferedReader br;
          String accinfo;
          boolean exist=false;
             try{          
                                   
                                    fr=new FileReader(filename);
                                    br=new BufferedReader(fr);
                                    while ((accinfo=br.readLine())!=null){
           
                                    if(check(accinfo,username))
                                    {
                                                 JOptionPane.showMessageDialog(null, "User Already Exists");
                                                exist=true;
                                                break;
                                    }else{
                                    
                                        
                                    }
                                   
             
                                     }
           
                        br.close();
           fr.close();    
     } catch(IOException | HeadlessException ie){System.out.println("Error!");}
                return exist;
    }
    
    public boolean check(String line,String input) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
      
        
        String[] info=line.split("-");
                        String data=info[0];
                return data.equals(input);
    }

    public void saveToFile(String fileName, String info) {
        
         //To change body of generated methods, choose Tools | Templates.
    try{
                        FileWriter fw=new FileWriter(fileName,true); 
        try (BufferedWriter bw = new BufferedWriter(fw)) {
            bw.write(info);
            bw.newLine();
            bw.flush();
            bw.close();
            // showMess("The account is created.",msgLabel);
        }
                        
                        // JOptionPane.showMessageDialog(null, "You have been registered successfully!");
                         
                         int input = JOptionPane.showOptionDialog(null, "You have registered successfully","visitor registration",  JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                          if(input==JOptionPane.OK_OPTION){
                               setVisible(false);
        admin_menu r = new admin_menu();
        r.setVisible(true);
        r.setLocationRelativeTo(null);
                          }else if(input==JOptionPane.CANCEL_OPTION){
                              setVisible(false);
        admin_menu r = new admin_menu();
        r.setVisible(true);
        r.setLocationRelativeTo(null);
                          }
                       
             }catch(IOException ie){System.out.println("Error in writing to file...");} 
    }
}
